// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_16d41c6fc5b8bf5d
#define INCLUDED_16d41c6fc5b8bf5d
#include "maglev/MagLev.h"
#endif
#ifndef INCLUDED_carloancalculator_CarLoanCalculator
#include <carloancalculator/CarLoanCalculator.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_bbfaa45385015fd2_15_new,"carloancalculator.CarLoanCalculator","new",0x80048a30,"carloancalculator.CarLoanCalculator.new","carloancalculator/CarLoanCalculator.hx",15,0x513d31c1)
HX_LOCAL_STACK_FRAME(_hx_pos_bbfaa45385015fd2_11_boot,"carloancalculator.CarLoanCalculator","boot",0x7c0d6062,"carloancalculator.CarLoanCalculator.boot","carloancalculator/CarLoanCalculator.hx",11,0x513d31c1)
namespace carloancalculator{

void CarLoanCalculator_obj::__construct( ::maglev::MagLev maglev){
            	HX_STACKFRAME(&_hx_pos_bbfaa45385015fd2_15_new)
HXDLIN(  15)		this->maglev = maglev;
            	}

Dynamic CarLoanCalculator_obj::__CreateEmpty() { return new CarLoanCalculator_obj; }

void *CarLoanCalculator_obj::_hx_vtable = 0;

Dynamic CarLoanCalculator_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< CarLoanCalculator_obj > _hx_result = new CarLoanCalculator_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool CarLoanCalculator_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x57fae3e0;
}


::hx::ObjectPtr< CarLoanCalculator_obj > CarLoanCalculator_obj::__new( ::maglev::MagLev maglev) {
	::hx::ObjectPtr< CarLoanCalculator_obj > __this = new CarLoanCalculator_obj();
	__this->__construct(maglev);
	return __this;
}

::hx::ObjectPtr< CarLoanCalculator_obj > CarLoanCalculator_obj::__alloc(::hx::Ctx *_hx_ctx, ::maglev::MagLev maglev) {
	CarLoanCalculator_obj *__this = (CarLoanCalculator_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(CarLoanCalculator_obj), true, "carloancalculator.CarLoanCalculator"));
	*(void **)__this = CarLoanCalculator_obj::_hx_vtable;
	__this->__construct(maglev);
	return __this;
}

CarLoanCalculator_obj::CarLoanCalculator_obj()
{
}

void CarLoanCalculator_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(CarLoanCalculator);
	HX_MARK_MEMBER_NAME(maglev,"maglev");
	HX_MARK_END_CLASS();
}

void CarLoanCalculator_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(maglev,"maglev");
}

::hx::Val CarLoanCalculator_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"maglev") ) { return ::hx::Val( maglev ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val CarLoanCalculator_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"maglev") ) { maglev=inValue.Cast<  ::maglev::MagLev >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void CarLoanCalculator_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("maglev",2a,df,2b,b3));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo CarLoanCalculator_obj_sMemberStorageInfo[] = {
	{::hx::fsUnknown /*  ::maglev::MagLev */ ,(int)offsetof(CarLoanCalculator_obj,maglev),HX_("maglev",2a,df,2b,b3)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *CarLoanCalculator_obj_sStaticStorageInfo = 0;
#endif

static ::String CarLoanCalculator_obj_sMemberFields[] = {
	HX_("maglev",2a,df,2b,b3),
	::String(null()) };

::hx::Class CarLoanCalculator_obj::__mClass;

void CarLoanCalculator_obj::__register()
{
	CarLoanCalculator_obj _hx_dummy;
	CarLoanCalculator_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("carloancalculator.CarLoanCalculator",3e,f2,8f,c2);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(CarLoanCalculator_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< CarLoanCalculator_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = CarLoanCalculator_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = CarLoanCalculator_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void CarLoanCalculator_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_bbfaa45385015fd2_11_boot)
HXDLIN(  11)		__mClass->__meta__ =  ::Dynamic(::hx::Anon_obj::Create(1)
            			->setFixed(0,HX_("obj",f7,8f,54,00), ::Dynamic(::hx::Anon_obj::Create(1)
            				->setFixed(0,HX_("SuppressWarnings",0c,d3,d2,00),::cpp::VirtualArray_obj::__new(1)->init(0,::cpp::VirtualArray_obj::__new(4)->init(0,HX_("checkstyle:FieldDocComment",70,56,1b,20))->init(1,HX_("checkstyle:LocalVariableName",c1,ac,a3,03))->init(2,HX_("checkstyle:MultipleStringLiterals",d6,ed,13,79))->init(3,HX_("checkstyle:MagicNumber",a5,aa,f4,8b)))))));
            	}
}

} // end namespace carloancalculator
