// Generated by Haxe 4.1.1
#ifndef INCLUDED_carloancalculator_CarLoanCalculator
#define INCLUDED_carloancalculator_CarLoanCalculator

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_16d41c6fc5b8bf5d
#define INCLUDED_16d41c6fc5b8bf5d
#include "maglev/MagLev.h"
#endif
HX_DECLARE_CLASS1(carloancalculator,CarLoanCalculator)

namespace carloancalculator{


class HXCPP_CLASS_ATTRIBUTES CarLoanCalculator_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef CarLoanCalculator_obj OBJ_;
		CarLoanCalculator_obj();

	public:
		enum { _hx_ClassId = 0x57fae3e0 };

		void __construct( ::maglev::MagLev maglev);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="carloancalculator.CarLoanCalculator")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"carloancalculator.CarLoanCalculator"); }
		static ::hx::ObjectPtr< CarLoanCalculator_obj > __new( ::maglev::MagLev maglev);
		static ::hx::ObjectPtr< CarLoanCalculator_obj > __alloc(::hx::Ctx *_hx_ctx, ::maglev::MagLev maglev);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~CarLoanCalculator_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("CarLoanCalculator",66,aa,ab,18); }

		static void __boot();
		static  ::Dynamic __meta__;
		 ::maglev::MagLev maglev;
};

} // end namespace carloancalculator

#endif /* INCLUDED_carloancalculator_CarLoanCalculator */ 
